<Project>
  <PropertyGroup>
    <HHTargetFramework>net9.0</HHTargetFramework>
	<TargetFramework>$(HHTargetFramework)-windows</TargetFramework>
	<DevExpressVersion>24.2</DevExpressVersion>
    <Nullable>disable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>